version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: rag
      POSTGRES_DB: ragdb
    ports: ["5432:5432"]
    healthcheck: { test: ["CMD-SHELL", "pg_isready -U rag"], interval: 5s, timeout: 3s, retries: 10 }
